export const TOGGLE_DARK_THEME = "TOGGLE_DARK_THEME"

export const GET_SIMPLE_USERS = "GET_SIMPLE_USERS"
export const GET_USERS = "GET_USERS"
export const SIMPLE_USER_CREATED = "SIMPLE_USERS_CREATED"
export const USER_CREATED = "USER_CREATED"

export const ADD_TO_CART = "ADD_TO_CART"
export const CHECKOUT_REQUEST = "CHECKOUT_REQUEST"
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS"
export const CHECKOUT_FAILURE = "CHECKOUT_FAILURE"
export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS"
