export default {
  GET_USERS: "GET_USERS",
  GET_SIMPLE_USERS: "GET_SIMPLE_USERS",
  SIMPLE_USER_CREATED: "SIMPLE_USERS_CREATED",
  USER_CREATED: "USER_CREATED",

  ADD_TO_CART: "ADD_TO_CART",
  CHECKOUT_REQUEST: "CHECKOUT_REQUEST",
  CHECKOUT_SUCCESS: "CHECKOUT_SUCCESS",
  CHECKOUT_FAILURE: "CHECKOUT_FAILURE",
  RECEIVE_PRODUCTS: "RECEIVE_PRODUCTS"
}
